name: Python package tests

on:
  push:
  pull_request:
    types: [opened, reopened]
  schedule:
    - cron: "0 12 * * 1"
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  call-run-python-tests:
    uses: openclimatefix/.github/.github/workflows/python-test.yml@main
    with:
      # pytest-cov looks at this folder
      pytest_cov_dir: "quartz_solar_forecast"
      os_list: '["ubuntu-latest"]'
      python-version: "['3.10','3.11']"
      extra_commands: echo "HF_TOKEN=${{ vars.HF_TOKEN }}" > .env
      pytest_numcpus: '1'
